export const LOGOS = [
  {
    id: 'dog-walking',
    image: '/logos/dog-walking.png',
    tags: ['animal', 'service'],
    layout: 'horizontal',
  },
  {
    id: 'lawyer',
    image: '/logos/lawyer.png',
    tags: ['professional', 'legal'],
    layout: 'vertical',
  },
  {
    id: 'interior',
    image: '/logos/interior.png',
    tags: ['creative', 'design'],
    layout: 'horizontal',
  },
  {
    id: 'japanese',
    image: '/logos/japanese.png',
    tags: ['language', 'culture'],
    layout: 'vertical',
  },
  {
    id: 'arizona',
    image: '/logos/arizona.png',
    tags: ['location', 'nature'],
    layout: 'horizontal',
  },
  {
    id: 'cafe',
    image: '/logos/cafe.png',
    tags: ['food', 'drink'],
    layout: 'vertical',
  },
  {
    id: 'cleaner',
    image: '/logos/cleaner.png',
    tags: ['service', 'household'],
    layout: 'horizontal',
  },
  {
    id: 'cleaning',
    image: '/logos/cleaning.png',
    tags: ['service', 'household'],
    layout: 'vertical',
  },
  {
    id: 'dentist',
    image: '/logos/dentist.png',
    tags: ['professional', 'health'],
    layout: 'horizontal',
  },
  {
    id: 'designer',
    image: '/logos/designer.png',
    tags: ['creative', 'design'],
    layout: 'vertical',
  },
  {
    id: 'dog-walker',
    image: '/logos/dog-walker.png',
    tags: ['animal', 'service'],
    layout: 'horizontal',
  },
  {
    id: 'photoluke',
    image: '/logos/photoluke.png',
    tags: ['personal', 'photography'],
    layout: 'vertical',
  },
  {
    id: 'fitness',
    image: '/logos/fitness.png',
    tags: ['health', 'sport'],
    layout: 'horizontal',
  },
  {
    id: 'insurances',
    image: '/logos/insurances.png',
    tags: ['financial', 'security'],
    layout: 'vertical',
  },
  {
    id: 'matcha',
    image: '/logos/matcha.png',
    tags: ['food', 'drink'],
    layout: 'horizontal',
  },
  {
    id: 'photographer',
    image: '/logos/photographer.png',
    tags: ['professional', 'photography'],
    layout: 'vertical',
  },
  {
    id: 'podcast',
    image: '/logos/podcast.png',
    tags: ['media', 'audio'],
    layout: 'horizontal',
  },
  {
    id: 'real-estate',
    image: '/logos/real-estate.png',
    tags: ['business', 'property'],
    layout: 'vertical',
  },
  {
    id: 'spanish',
    image: '/logos/spanish.png',
    tags: ['language', 'culture'],
    layout: 'horizontal',
  },
  {
    id: 'tea',
    image: '/logos/tea.png',
    tags: ['food', 'drink'],
    layout: 'vertical',
  },
  {
    id: 'security',
    image: '/logos/security.png',
    tags: ['business', 'protection'],
    layout: 'horizontal',
  },
  {
    id: 'tiny-cafe',
    image: '/logos/tiny-cafe.png',
    tags: ['food', 'drink'],
    layout: 'vertical',
  },
  {
    id: 'taxi',
    image: '/logos/taxi.png',
    tags: ['transport', 'service'],
    layout: 'horizontal',
  },
  {
    id: 'gym',
    image: '/logos/gym.png',
    tags: ['health', 'sport'],
    layout: 'vertical',
  },
];
