export const CITIES = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'Charlotte',
  'San Francisco',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington, D.C.',
  'Boston',
  'El Paso',
  'Nashville',
  'Detroit',
  'Oklahoma City',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Kansas City',
  'Long Beach',
  'Mesa',
  'Atlanta',
  'Colorado Springs',
  'Virginia Beach',
  'Raleigh',
  'Omaha',
  'Miami',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Wichita',
  'New Orleans',
  'Arlington',
  'Tampa',
  'Anaheim',
  'Cleveland',
  'Aurora',
  'Santa Ana',
  'Riverside',
  'Corpus Christi',
  'Lexington',
  'Anchorage',
  'Stockton',
  'St. Paul',
  'Cincinnati',
  'Henderson',
  'Greensboro',
  'Plano',
  'Newark',
  'Toledo',
  'Lincoln',
  'Orlando',
  'Chula Vista',
  'Jersey City',
  'Chandler',
  'Fort Wayne',
  'Buffalo',
  'Durham',
  'St. Petersburg',
  'Irvine',
  'Laredo',
  'Lubbock',
  'Madison',
  'Gilbert',
  'Norfolk',
  'Reno',
  'Winston-Salem',
  'Glendale',
  'Hialeah',
  'Garland',
  'Scottsdale',
  'Irving',
  'Chesapeake',
  'North Las Vegas',
  'Fremont',
  'Baton Rouge',
  'Richmond',
  'Boise',
  'San Bernardino',
  'Spokane',
  'Des Moines',
];
